configs:
  caddyfile:
    file: ./Caddyfile
  authelia:
    file: ./configuration.yml

networks:
  db:
  ldap:
  authelia:
  silicon:
  nextcloud:
  yarr:

volumes:
  db:
  lldap_data:
  authelia_config:
  silicon_instance:
  caddy_data:
  caddy_config:
  nextcloud:
  yarr:

services:
  db:
    image: docker.io/postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db
    volumes:
      - "db:/var/lib/postgresql/data"
    restart: unless-stopped

  lldap:
    # Identifies as 0.4.2-alpha
    # Check with: docker run --rm -ti nitnelave/lldap --version
    image: docker.io/nitnelave/lldap@sha256:926c7576b12e90546c10a01349ed5ee8e9921863719e8db5ea15b15957f4639e
    environment:
      - TZ=America/Detroit
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_LDAP_BASE_DN=${LLDAP_LDAP_BASE_DN}
    ports:
      - "127.0.0.1:17170:17170"
    networks:
      - ldap
    volumes:
      - "lldap_data:/data"
    restart: unless-stopped

  authelia:
    image: docker.io/authelia/authelia:4.37.5
    environment:
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    configs:
      - source: authelia
        target: /config/configuration.yml
    depends_on:
      - lldap
    networks:
      - ldap
      - authelia
    volumes:
      - "authelia_config:/config"
    restart: unless-stopped

  silicon:
    image: docker.io/bityard/silicon
    networks:
      - silicon
    volumes:
      - silicon_instance:/home/silicon/instance
    restart: unless-stopped

  caddy:
    image: docker.io/caddy:2.6.2
    environment:
      AUTH_FQDN: ${AUTH_FQDN}
      SILICON_FQDN: ${SILICON_FQDN}
      NEXTCLOUD_FQDN: ${NEXTCLOUD_FQDN}
      IPV4_FQDN: ${IPV4_FQDN}
      YARR_FQDN: ${YARR_FQDN}
      ROOT_DN: ${ROOT_DN}
      ROOT_REDIRECT: ${ROOT_REDIRECT}
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    depends_on:
      - authelia
      - silicon
      - nextcloud
    ports:
      - "80:80"
      - "443:443"
    networks:
      - authelia
      - silicon
      - nextcloud
      - yarr
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  nextcloud: &nextcloud
    image: docker.io/nextcloud:27.1.4
    environment:
      TZ: ${TZ}
      NEXTCLOUD_DBTYPE: ${NEXTCLOUD_DBTYPE}
      NEXTCLOUD_DBHOST: ${NEXTCLOUD_DBHOST}
      NEXTCLOUD_DBUSER: ${NEXTCLOUD_DBUSER}
      NEXTCLOUD_DBPASSWORD: ${NEXTCLOUD_DBPASSWORD}
      NEXTCLOUD_DBNAME: ${NEXTCLOUD_DBNAME}
      NEXTCLOUD_DBTABLEPREFIX: ${NEXTCLOUD_DBTABLEPREFIX}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTHTYPE: ${SMTP_AUTHTYPE}
      SMTP_NAME: ${SMTP_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
    depends_on:
      - db
    networks:
      - db
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped

  nextcloud-cron:
    <<: *nextcloud
    entrypoint: /cron.sh

  yarr:
    image: ghcr.io/wakeful-cloud/yarr:sha-d15b43b
    networks:
      - yarr
    volumes:
      - yarr:/data
    restart: unless-stopped
