services:
  silicon:
    image: bityard/silicon
    build: .
    init: true
    volumes:
      - silicon_instance:/home/silicon/instance

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - silicon
    environment:
      - BASICAUTH_USER: ${BASICAUTH_USER}
      - BASICAUTH_PW: ${BASICAUTH_PW}

volumes:
  silicon_instance:
  caddy_data:
  caddy_config:
